<?
$aMenuLinks = Array(
    Array(
        "Обои",
        "/oboi/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Краски",
        "/kraski/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Лепнина",
        "/lepnina/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Текстиль",
        "/tekstil/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Акции",
        "/akzii/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "/novosti/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "О нас",
        "/o-nas/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнерам",
        "/partneram/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Дизайнерам",
        "/dizaineram/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/kontakty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Карта сайта",
        "/karta_saita/",
        Array(),
        Array(),
        ""
    )
);
?>